# -*- coding: utf-8 -*-
import collections


def float_or_float_list():
    return True


def yes_no():
    return True


def one_of(x):
    return True


def nonnegative_integer():
    return True


Field = collections.namedtuple(
    "Field",
    "key aliases valid_fn default terminator",
    defaults=(None, [], float_or_float_list, None, ";"),
)
RenamePair = collections.namedtuple("RenamePair", "key alias")

CA_540_2020 = dict(
    input_wrap=(
        Field(key="Title:", terminator="\n"),
        Field(key="FileName", terminator="\n"),
        Field(key="L6", default="no", terminator="\n"),
        Field(key="L8", default=0, terminator="\n"),
        Field(key="L9", default=0, terminator="\n"),
        Field(key="L10", default=0, terminator="\n"),
        Field(key="L12"),
        Field(key="CA540_Subtr_A1"),
        Field(key="CA540_Addit_A1"),
        Field(key="CA540_Subtr_A2"),
        Field(key="CA540_Addit_A2"),
        Field(key="CA540_Subtr_A3"),
        Field(key="CA540_Addit_A3"),
        Field(key="CA540_Subtr_A4"),
        Field(key="CA540_Addit_A4"),
        Field(key="CA540_Subtr_A5"),
        Field(key="CA540_Addit_A5"),
        Field(key="CA540_Subtr_A7"),
        Field(key="CA540_Addit_A7"),
        Field(key="CA540_Subtr_B1"),
        Field(key="CA540_Addit_B2"),
        Field(key="CA540_Subtr_B3"),
        Field(key="CA540_Addit_B3"),
        Field(key="CA540_Subtr_B4"),
        Field(key="CA540_Addit_B4"),
        Field(key="CA540_Subtr_B5"),
        Field(key="CA540_Addit_B5"),
        Field(key="CA540_Subtr_B6"),
        Field(key="CA540_Addit_B6"),
        Field(key="CA540_Subtr_B7"),
        Field(key="CA540_Subtr_B8a"),
        Field(key="CA540_Subtr_B8b"),
        Field(key="CA540_Addit_B8c"),
        Field(key="CA540_Subtr_B8d"),
        Field(key="CA540_Subtr_B8e"),
        Field(key="CA540_Subtr_B8f"),
        Field(key="CA540_Addit_B8f"),
        Field(key="CA540_Subtr_B8g"),
        Field(key="CA540_Subtr_C10"),
        Field(key="CA540_Subtr_C11"),
        Field(key="CA540_Addit_C11"),
        Field(key="CA540_Subtr_C12"),
        Field(key="CA540_Addit_C13"),
        Field(key="CA540_Subtr_C14"),
        Field(key="CA540_Subtr_C16"),
        Field(key="CA540_Addit_C18"),
        Field(key="CA540_Addit_C20"),
        Field(key="CA540_Subtr_C21"),
        Field(key="CA540_P2_Sub_5a"),
        Field(key="CA540_P2_Sub_6"),
        Field(key="CA540_P2_Add_6"),
        Field(key="CA540_P2_Add_8a"),
        Field(key="CA540_P2_Add_8b"),
        Field(key="CA540_P2_Add_8c"),
        Field(key="CA540_P2_Sub_8d"),
        Field(key="CA540_P2_Sub_9"),
        Field(key="CA540_P2_Add_9"),
        Field(key="CA540_P2_Sub_11"),
        Field(key="CA540_P2_Add_11"),
        Field(key="CA540_P2_Sub_12"),
        Field(key="CA540_P2_Add_12"),
        Field(key="CA540_P2_Sub_13"),
        Field(key="CA540_P2_Add_13"),
        Field(key="CA540_P2_Sub_15"),
        Field(key="CA540_P2_Add_15"),
        Field(key="CA540_P2_Sub_16"),
        Field(key="CA540_P2_Add_16"),
        Field(key="CA540_P2_19"),
        Field(key="CA540_P2_20"),
        Field(key="CA540_P2_21"),
        Field(key="L34"),
        Field(key="L40"),
        Field(key="L43"),
        Field(key="L44"),
        Field(key="L45"),
        Field(key="L46"),
        Field(key="L61"),
        Field(key="L62"),
        Field(key="L63"),
        Field(key="L64"),
        Field(key="L71"),
        Field(key="L72"),
        Field(key="L73"),
        Field(key="L74"),
        Field(key="L75"),
        Field(key="L76"),
        Field(key="L77"),
        Field(key="L91"),
        Field(key="L92"),
        Field(key="L112"),
        Field(key="L113"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="Town:", terminator="\n"),
        Field(key="Zipcode:", terminator="\n"),
        Field(key="YourDOB:", terminator="\n"),
        Field(key="SpouseDOB:", terminator="\n"),
    ),
    output_wrap=(),
)

US_1040_2020 = dict(
    input_wrap=(
        Field(
            key="Title:",
            aliases="title",
            terminator="\n",
        ),
        Field(
            key="Status",
            aliases=("status", "filing_status"),
            valid_fn=one_of(
                frozenset(
                    (
                        "Single",
                        "Married/Joint",
                        "Head_of_House",
                        "Married/Sep",
                        "Widow(er)",
                    )
                )
            ),
            default="Single",
            terminator="\n",
        ),
        Field(
            key="You_65+Over?",
            aliases="you_are_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="You_Blind?",
            aliases="you_are_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_65+Over?",
            aliases="spouse_is_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_Blind?",
            aliases="spouse_is_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Dependents",
            aliases="num_dependents",
            valid_fn=nonnegative_integer,
            default=1,
            terminator="\n",
        ),
        Field(
            key="VirtCurr?",
            aliases="bought_virtual_currency",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(key="L1", aliases=("wages", "wages_salaries_tips", "w2_box_1")),
        Field(key="L2a", aliases=("tax_exempt_interest",)),
        Field(
            key="L2b",
            aliases=(
                "interest",
                "1099_int_box_1",
                "1099_interest",
            ),
        ),
        Field(
            key="L3a",
            aliases=(
                "qualified_dividends",
                "1099_div_box_1b",
            ),
        ),
        Field(
            key="L3b",
            aliases=(
                "ordinary_dividends",
                "1099_div_box_1a",
            ),
        ),
        Field(key="L4a"),
        Field(key="L4b"),
        Field(key="L5a"),
        Field(key="L5b"),
        Field(key="L6a"),
        Field(key="L13"),
        Field(key="L19"),
        Field(key="L25a"),
        Field(key="L25b"),
        Field(key="L25c"),
        Field(key="L26"),
        Field(key="L27"),
        Field(key="L28"),
        Field(key="L29"),
        Field(key="L30"),
        Field(key="L38"),
        Field(
            key="CapGains-A/D",
            aliases=(
                "capital_gains_a_d",
                "cap_gains_a_d",
                "capital_gains_basis_reported",
                "form_8949_check_a_or_d",
            ),
        ),
        Field(key="CapGains-B/E"),
        Field(key="CapGains-C/F"),
        Field(key="D4"),
        Field(key="D5"),
        Field(key="D6"),
        Field(key="D11"),
        Field(key="D12"),
        Field(key="D13"),
        Field(key="D14"),
        Field(key="D19"),
        Field(key="Collectibles"),
        Field(key="S1_1"),
        Field(key="S1_2a"),
        Field(key="S1_2b:", terminator="\n"),
        Field(key="S1_3"),
        Field(key="S1_4"),
        Field(key="S1_5"),
        Field(key="S1_6"),
        Field(key="S1_7"),
        Field(key="S1_8"),
        Field(key="S1_8_Type:", terminator="\n"),
        Field(key="S1_10"),
        Field(key="S1_11"),
        Field(key="S1_12"),
        Field(key="S1_13"),
        Field(key="S1_14"),
        Field(key="S1_15"),
        Field(key="S1_16"),
        Field(key="S1_17"),
        Field(key="S1_18a"),
        Field(key="AlimRecipSSN:", terminator="\n"),
        Field(key="AlimRecipName:", terminator="\n"),
        Field(key="S1_19"),
        Field(key="S1_20"),
        Field(key="S1_21"),
        Field(key="A1"),
        Field(key="A5a"),
        Field(key="CheckBoxA5a"),
        Field(key="A5b"),
        Field(key="A5c"),
        Field(key="A6"),
        Field(key="A8a"),
        Field(key="A8b"),
        Field(key="A8c"),
        Field(key="A8d"),
        Field(key="A9"),
        Field(key="A11"),
        Field(key="A12"),
        Field(key="A13"),
        Field(key="A15"),
        Field(key="A16"),
        Field(key="A18"),
        Field(key="B7a"),
        Field(key="B7aa"),
        Field(key="B7b"),
        Field(key="B8"),
        Field(key="AMTws2c"),
        Field(key="AMTws2g"),
        Field(key="AMTws3"),
        Field(key="AMTws8"),
        Field(key="S2_2"),
        Field(key="S2_4"),
        Field(key="S2_5"),
        Field(key="S2_6"),
        Field(key="S2_7a"),
        Field(key="S2_7b"),
        Field(key="S2_8"),
        Field(key="S2_9"),
        Field(key="S3_1"),
        Field(key="S3_2"),
        Field(key="S3_3"),
        Field(key="S3_4"),
        Field(key="S3_5"),
        Field(key="S3_6"),
        Field(key="S3_8"),
        Field(key="S3_9"),
        Field(key="S3_10"),
        Field(key="S3_11"),
        Field(key="S3_12a"),
        Field(key="S3_12b"),
        Field(key="S3_12c"),
        Field(key="S3_12d"),
        Field(key="S3_12e"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="Town/City:", terminator="\n"),
        Field(key="State:", terminator="\n"),
        Field(key="ZipCode:", terminator="\n"),
        Field(key="YourOccupat:", terminator="\n"),
        Field(key="SpouseOccupat:", terminator="\n"),
        Field(key="Dep1_FirstName:", terminator="\n"),
        Field(key="Dep1_LastName:", terminator="\n"),
        Field(key="Dep1_SocSec#:", terminator="\n"),
        Field(key="Dep1_Relation:", terminator="\n"),
        Field(key="CkDep1_ChildTxCrd:", terminator="\n"),
        Field(key="CkDep1_CrdOtherDep:", terminator="\n"),
        Field(key="Dep2_FirstName:", terminator="\n"),
        Field(key="Dep2_LastName:", terminator="\n"),
        Field(key="Dep2_SocSec#:", terminator="\n"),
        Field(key="Dep2_Relation:", terminator="\n"),
        Field(key="CkDep2_ChildTxCrd:", terminator="\n"),
        Field(key="CkDep2_CrdOtherDep:", terminator="\n"),
        Field(key="Dep3_FirstName:", terminator="\n"),
        Field(key="Dep3_LastName:", terminator="\n"),
        Field(key="Dep3_SocSec#:", terminator="\n"),
        Field(key="Dep3_Relation:", terminator="\n"),
        Field(key="CkDep3_ChildTxCrd:", terminator="\n"),
        Field(key="CkDep3_CrdOtherDep:", terminator="\n"),
        Field(key="Dep4_FirstName:", terminator="\n"),
        Field(key="Dep4_LastName:", terminator="\n"),
        Field(key="Dep4_SocSec#:", terminator="\n"),
        Field(key="Dep4_Relation:", terminator="\n"),
        Field(key="CkDep4_ChildTxCrd:", terminator="\n"),
        Field(key="CkDep4_CrdOtherDep:", terminator="\n"),
        Field(key="CkMoreThan_4_Dependents:", terminator="\n"),
    ),
    output_wrap=(
        RenamePair(key="L9", alias="total_income"),
        RenamePair(key="L11", alias="agi"),
        RenamePair(key="Your Alternative Minimum Tax", alias="amt"),
        RenamePair(key="L15", alias="taxable_income"),
        RenamePair(key="L24", alias="total_tax"),
        RenamePair(key="L33", alias="total_payments"),
        RenamePair(key="L23", alias="tax_owed"),
    ),
)

US_1040_2019 = dict(
    input_wrap=(
        Field(
            key="Title:",
            aliases="title",
            terminator="\n",
        ),
        Field(
            key="Status",
            aliases=("status", "filing_status"),
            valid_fn=one_of(
                frozenset(
                    (
                        "Single",
                        "Married/Joint",
                        "Head_of_House",
                        "Married/Sep",
                        "Widow(er)",
                    )
                )
            ),
            default="Single",
            terminator="\n",
        ),
        Field(
            key="You_65+Over?",
            aliases="you_are_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="You_Blind?",
            aliases="you_are_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_65+Over?",
            aliases="spouse_is_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_Blind?",
            aliases="spouse_is_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Dependents",
            aliases="num_dependents",
            valid_fn=nonnegative_integer,
            default=1,
            terminator="\n",
        ),
        Field(key="L1", aliases=("wages", "wages_salaries_tips", "w2_box_1")),
        Field(key="L2a", aliases=("tax_exempt_interest",)),
        Field(
            key="L2b",
            aliases=(
                "interest",
                "1099_int_box_1",
                "1099_interest",
            ),
        ),
        Field(
            key="L3a",
            aliases=(
                "qualified_dividends",
                "1099_div_box_1b",
            ),
        ),
        Field(
            key="L3b",
            aliases=(
                "ordinary_dividends",
                "1099_div_box_1a",
            ),
        ),
        Field(key="L4a", aliases=("ira_distributions",)),
        Field(key="L4b", aliases=("taxable_ira_distributions",)),
        Field(key="L4c"),
        Field(key="L4d"),
        Field(key="L5a"),
        Field(key="L10"),
        Field(key="L13a"),
        Field(key="L17"),
        Field(key="L18a"),
        Field(key="L18b"),
        Field(key="L18c"),
        Field(key="L24"),
        Field(key="CapGains-A/D"),
        Field(key="CapGains-B/E"),
        Field(key="CapGains-C/F"),
        Field(key="D4"),
        Field(key="D5"),
        Field(key="D6"),
        Field(key="D11"),
        Field(key="D12"),
        Field(key="D13"),
        Field(key="D14"),
        Field(key="Collectibles"),
        Field(key="VirtCurr?", default="N", terminator="\n"),
        Field(key="S1_1"),
        Field(key="S1_2a"),
        Field(key="S1_2b:", terminator="\n"),
        Field(key="S1_3"),
        Field(key="S1_4"),
        Field(key="S1_5"),
        Field(key="S1_6"),
        Field(key="S1_7"),
        Field(key="S1_8"),
        Field(key="S1_8_Type:", terminator="\n"),
        Field(key="S1_10"),
        Field(key="S1_11"),
        Field(key="S1_12"),
        Field(key="S1_13"),
        Field(key="S1_14"),
        Field(key="S1_15"),
        Field(key="S1_16"),
        Field(key="S1_17"),
        Field(key="S1_18a"),
        Field(key="AlimRecipSSN:", terminator="\n"),
        Field(key="AlimRecipName:", terminator="\n"),
        Field(key="S1_19"),
        Field(key="S1_20"),
        Field(key="S1_21"),
        Field(key="A1"),
        Field(key="A5a"),
        Field(key="A5b"),
        Field(key="A5c"),
        Field(key="A6"),
        Field(key="A8a"),
        Field(key="A8b"),
        Field(key="A8c"),
        Field(key="A9"),
        Field(key="A11"),
        Field(key="A12"),
        Field(key="A13"),
        Field(key="A15"),
        Field(key="A16"),
        Field(key="B7a", default="N"),
        Field(key="B7aa"),
        Field(key="B7b"),
        Field(key="B8", default="N"),
        Field(key="AMTws2c"),
        Field(key="AMTws2g"),
        Field(key="S2_2"),
        Field(key="S2_4"),
        Field(key="S2_5"),
        Field(key="S2_6"),
        Field(key="S2_7a"),
        Field(key="S2_7b"),
        Field(key="S2_8"),
        Field(key="S2_9"),
        Field(key="S3_1"),
        Field(key="S3_2"),
        Field(key="S3_3"),
        Field(key="S3_4"),
        Field(key="S3_5"),
        Field(key="S3_6"),
        Field(key="S3_8"),
        Field(key="S3_9"),
        Field(key="S3_10"),
        Field(key="S3_11"),
        Field(key="S3_12"),
        Field(key="S3_13"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="TownStateZip:", terminator="\n"),
    ),
    output_wrap=(
        RenamePair(key="L7b", alias="total_income"),
        RenamePair(key="L8b", alias="agi"),
        RenamePair(key="Your Alternative Minimum Tax", alias="amt"),
        RenamePair(key="L11", alias="taxable_income"),
        RenamePair(key="L16", alias="total_tax"),
        RenamePair(key="L19", alias="total_payments"),
        RenamePair(key="L23", alias="tax_owed"),
    ),
)


US_1040_2018 = dict(
    input_wrap=(
        Field(
            key="Title:",
            aliases="title",
            terminator="\n",
        ),
        Field(
            key="Status",
            aliases=("status", "filing_status"),
            valid_fn=one_of(
                frozenset(
                    (
                        "Single",
                        "Married/Joint",
                        "Head_of_House",
                        "Married/Sep",
                        "Widow(er)",
                    )
                )
            ),
            default="Single",
            terminator="\n",
        ),
        Field(
            key="You_65+Over?",
            aliases="you_are_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="You_Blind?",
            aliases="you_are_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_65+Over?",
            aliases="spouse_is_over_65",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="Spouse_Blind?",
            aliases="spouse_is_blind",
            valid_fn=yes_no,
            default="N",
            terminator="\n",
        ),
        Field(
            key="HealthCoverage?",
            aliases="have_health_coverage",
            valid_fn=yes_no,
            default="Y",
            terminator="\n",
        ),
        Field(
            key="Dependents",
            aliases="num_dependents",
            valid_fn=nonnegative_integer,
            default=1,
            terminator="\n",
        ),
        Field(key="L1", aliases=("wages", "wages_salaries_tips", "w2_box_1")),
        Field(key="L2a", aliases=("tax_exempt_interest",)),
        Field(
            key="L2b",
            aliases=(
                "interest",
                "1099_int_box_1",
                "1099_interest",
            ),
        ),
        Field(
            key="L3a",
            aliases=(
                "qualified_dividends",
                "1099_div_box_1b",
            ),
        ),
        Field(
            key="L3b",
            aliases=(
                "ordinary_dividends",
                "1099_div_box_1a",
            ),
        ),
        Field(key="L4a", aliases=("ira_distributions",)),
        Field(key="L4b", aliases=("taxable_ira_distributions",)),
        Field(
            key="L5a",
            aliases=("social_security_benefits", "ss_benefits", "ssa_1099_box_5"),
        ),
        Field(
            key="L9",
            aliases=("qualified_business_income_deduction",),
        ),
        Field(
            key="L12a",
            aliases=("child_tax_credit",),
        ),
        Field(
            key="L16",
            aliases=(
                "withheld",
                "withholding",
                "federal_income_tax_withheld",
            ),
        ),
        Field(
            key="L17a",
            aliases=(
                "eic",
                "earned_income_credit",
            ),
        ),
        Field(
            key="L17b",
            aliases=("child_tax_credit", "schedule_8812_credit"),
        ),
        Field(
            key="L17c",
            aliases=("education_credit", "form_8863_credit"),
        ),
        Field(
            key="CapGains-A/D",
            aliases=(
                "capital_gains_a_d",
                "cap_gains_a_d",
                "capital_gains_basis_reported",
                "form_8949_check_a_or_d",
            ),
        ),
        Field(
            key="CapGains-B/E",
            aliases=(
                "capital_gains_b_e",
                "cap_gains_b_e",
                "capital_gains_basis_not_reported",
                "form_8949_check_b_or_e",
            ),
        ),
        Field(
            key="CapGains-C/F",
            aliases=("capital_gains_c_f", "cap_gains_c_f", "form_8949_check_c_or_f"),
        ),
        Field(key="D4"),
        Field(key="D5"),
        Field(key="D6"),
        Field(key="D11"),
        Field(key="D12"),
        Field(key="D13"),
        Field(key="D14"),
        Field(key="Collectibles"),
        Field(key="S1_10"),
        Field(key="S1_11"),
        Field(key="S1_12"),
        Field(key="S1_14"),
        Field(key="S1_17"),
        Field(key="S1_18"),
        Field(key="S1_19"),
        Field(key="S1_21"),
        Field(key="S1_23"),
        Field(key="S1_24"),
        Field(key="S1_25"),
        Field(key="S1_26"),
        Field(key="S1_27"),
        Field(key="S1_28"),
        Field(key="S1_29"),
        Field(key="S1_30"),
        Field(key="S1_31a"),
        Field(key="S1_32"),
        Field(key="S1_33"),
        Field(key="A1"),
        Field(key="A5a"),
        Field(key="A5b"),
        Field(key="A5c"),
        Field(key="A6"),
        Field(key="A8a"),
        Field(key="A8b"),
        Field(key="A8c"),
        Field(key="A9"),
        Field(key="A11"),
        Field(key="A12"),
        Field(key="A13"),
        Field(key="A15"),
        Field(key="A16"),
        Field(key="B7a", valid_fn=yes_no, default="N"),
        Field(key="B7aa"),
        Field(key="B7b"),
        Field(key="B8", valid_fn=yes_no, default="N"),
        Field(key="AMTws2c"),
        Field(key="AMTws2g"),
        Field(key="S2_46"),
        Field(key="S3_48"),
        Field(key="S3_49"),
        Field(key="S3_50"),
        Field(key="S3_51"),
        Field(key="S3_53"),
        Field(key="S3_54"),
        Field(key="S4_57"),
        Field(key="S4_58"),
        Field(key="S4_59"),
        Field(key="S4_60a"),
        Field(key="S4_60b"),
        Field(key="S4_61"),
        Field(key="S4_62"),
        Field(key="S4_63"),
        Field(key="S5_66"),
        Field(key="S5_70"),
        Field(key="S5_71"),
        Field(key="S5_72"),
        Field(key="S5_73"),
        Field(key="S5_74"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="TownStateZip:", terminator="\n"),
    ),
    output_wrap=(
        RenamePair(key="L6", alias="total_income"),
        RenamePair(key="L7", alias="agi"),
        RenamePair(key="Your Alternative Minimum Tax", alias="amt"),
        RenamePair(key="L10", alias="taxable_income"),
        RenamePair(key="L15", alias="total_tax"),
        RenamePair(key="L18", alias="total_payments"),
        RenamePair(key="L22", alias="tax_owed"),
    ),
)

US_1040_2017 = dict(
    input_wrap=(
        Field(
            key="Title:",
            aliases="title",
            terminator="\n",
        ),
        Field(
            key="Status",
            aliases=("status", "filing_status"),
            valid_fn=one_of(
                frozenset(
                    (
                        "Single",
                        "Married/Joint",
                        "Head_of_House",
                        "Married/Sep",
                        "Widow(er)",
                    )
                )
            ),
            default="Single",
            terminator="\n",
        ),
        Field(
            key="Under65?",
            aliases="you_are_under_65",
            default="Y",
            terminator="\n",
        ),
        Field(
            key="Dependents",
            aliases="num_dependents",
            valid_fn=nonnegative_integer,
            default=1,
            terminator="\n",
        ),
        Field(key="L7", aliases=("wages", "wages_salaries_tips", "w2_box_1")),
        Field(
            key="L8a",
            aliases=(
                "interest",
                "1099_int_box_1",
                "1099_interest",
            ),
        ),
        Field(key="L8b", aliases=("tax_exempt_interest",)),
        Field(
            key="L9",
            aliases=(
                "ordinary_dividends",
                "1099_div_box_1a",
            ),
        ),
        Field(
            key="L9b",
            aliases=(
                "qualified_dividends",
                "1099_div_box_1b",
            ),
        ),
        Field(key="L10"),
        Field(key="L11"),
        Field(key="L12"),
        Field(key="Collectibles"),
        Field(
            key="CapGains-A/D",
            aliases=(
                "capital_gains_a_d",
                "cap_gains_a_d",
                "capital_gains_basis_reported",
                "form_8949_check_a_or_d",
            ),
        ),
        Field(
            key="CapGains-B/E",
            aliases=(
                "capital_gains_b_e",
                "cap_gains_b_e",
                "capital_gains_basis_not_reported",
                "form_8949_check_b_or_e",
            ),
        ),
        Field(
            key="CapGains-C/F",
            aliases=("capital_gains_c_f", "cap_gains_c_f", "form_8949_check_c_or_f"),
        ),
        Field(key="D4"),
        Field(key="D5"),
        Field(key="D6"),
        Field(key="D11"),
        Field(key="D12"),
        Field(key="D13"),
        Field(key="D14"),
        Field(key="L14"),
        Field(key="L15a"),
        Field(key="L15b"),
        Field(key="L16a"),
        Field(key="L16b"),
        Field(key="L17"),
        Field(key="L18"),
        Field(key="L19"),
        Field(key="L20a"),
        Field(key="L21"),
        Field(key="L23"),
        Field(key="L24"),
        Field(key="L25"),
        Field(key="L26"),
        Field(key="L27"),
        Field(key="L28"),
        Field(key="L29"),
        Field(key="L30"),
        Field(key="L31a"),
        Field(key="L32"),
        Field(key="L33"),
        Field(key="L34"),
        Field(key="L35"),
        Field(key="L39a"),
        Field(key="A1"),
        Field(key="A5"),
        Field(key="A6"),
        Field(key="A7"),
        Field(key="A8"),
        Field(key="A10"),
        Field(key="A11"),
        Field(key="A12"),
        Field(key="A14"),
        Field(key="A16"),
        Field(key="A17"),
        Field(key="A18"),
        Field(key="A20"),
        Field(key="A21"),
        Field(key="A22"),
        Field(key="A23"),
        Field(key="A28"),
        Field(key="L46"),
        Field(key="L48"),
        Field(key="L49"),
        Field(key="L50"),
        Field(key="L51"),
        Field(key="L52"),
        Field(key="L53"),
        Field(key="L54"),
        Field(key="L57"),
        Field(key="L58"),
        Field(key="L59"),
        Field(key="L60a"),
        Field(key="L60b"),
        Field(key="L61"),
        Field(key="L62"),
        Field(key="L64"),
        Field(key="L65"),
        Field(key="L66a"),
        Field(key="L66b"),
        Field(key="L67"),
        Field(key="L68"),
        Field(key="L69"),
        Field(key="L70"),
        Field(key="L71"),
        Field(key="L72"),
        Field(key="L73"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="TownStateZip:", terminator="\n"),
    ),
    output_wrap=(
        RenamePair(key="L22", alias="total_income"),
        RenamePair(key="L37", alias="agi"),
        RenamePair(key="Your Alternative Minimum Tax", alias="amt"),
        RenamePair(key="L43", alias="taxable_income"),
        RenamePair(key="L63", alias="total_tax"),
        RenamePair(key="L74", alias="total_payments"),
        RenamePair(key="L78", alias="tax_owed"),
    ),
)

CA_540_2019 = dict(
    input_wrap=(
        Field(key="Title:", terminator="\n"),
        Field(key="FileName"),
        Field(key="L6"),
        Field(key="L8"),
        Field(key="L9"),
        Field(key="L10"),
        Field(key="L12"),
        Field(key="CA540_Subtr_A1"),
        Field(key="CA540_Addit_A1"),
        Field(key="CA540_Subtr_A2"),
        Field(key="CA540_Addit_A2"),
        Field(key="CA540_Subtr_A3"),
        Field(key="CA540_Addit_A3"),
        Field(key="CA540_Subtr_A4b"),
        Field(key="CA540_Addit_A4b"),
        Field(key="CA540_Subtr_A4d"),
        Field(key="CA540_Addit_A4d"),
        Field(key="CA540_Subtr_A6"),
        Field(key="CA540_Addit_A6"),
        Field(key="CA540_Subtr_B1"),
        Field(key="CA540_Addit_B2"),
        Field(key="CA540_Subtr_B3"),
        Field(key="CA540_Addit_B3"),
        Field(key="CA540_Subtr_B4"),
        Field(key="CA540_Addit_B4"),
        Field(key="CA540_Subtr_B5"),
        Field(key="CA540_Addit_B5"),
        Field(key="CA540_Subtr_B6"),
        Field(key="CA540_Addit_B6"),
        Field(key="CA540_Subtr_B7"),
        Field(key="CA540_Subtr_B8a"),
        Field(key="CA540_Subtr_B8b"),
        Field(key="CA540_Addit_B8c"),
        Field(key="CA540_Subtr_B8d"),
        Field(key="CA540_Subtr_B8e"),
        Field(key="CA540_Subtr_B8f"),
        Field(key="CA540_Addit_B8f"),
        Field(key="CA540_Subtr_B8g"),
        Field(key="CA540_Subtr_C10"),
        Field(key="CA540_Subtr_C11"),
        Field(key="CA540_Addit_C11"),
        Field(key="CA540_Subtr_C12"),
        Field(key="CA540_Addit_C13"),
        Field(key="CA540_Addit_C18"),
        Field(key="CA540_Addit_C20"),
        Field(key="CA540_Subtr_C21"),
        Field(key="CA540_P2_1"),
        Field(key="CA540_P2_Sub_5a"),
        Field(key="CA540_P2_Sub_6"),
        Field(key="CA540_P2_Add_8a"),
        Field(key="CA540_P2_Add_8b"),
        Field(key="CA540_P2_Add_8c"),
        Field(key="CA540_P2_Sub_9"),
        Field(key="CA540_P2_Add_9"),
        Field(key="CA540_P2_Sub_11"),
        Field(key="CA540_P2_Add_11"),
        Field(key="CA540_P2_Sub_12"),
        Field(key="CA540_P2_Add_12"),
        Field(key="CA540_P2_Sub_13"),
        Field(key="CA540_P2_Add_13"),
        Field(key="CA540_P2_Sub_15"),
        Field(key="CA540_P2_Add_15"),
        Field(key="CA540_P2_Sub_16"),
        Field(key="CA540_P2_Add_16"),
        Field(key="CA540_P2_19"),
        Field(key="CA540_P2_20"),
        Field(key="CA540_P2_21"),
        Field(key="L34"),
        Field(key="L40"),
        Field(key="L43"),
        Field(key="L44"),
        Field(key="L45"),
        Field(key="L46"),
        Field(key="L61"),
        Field(key="L62"),
        Field(key="L63"),
        Field(key="L71"),
        Field(key="L72"),
        Field(key="L73"),
        Field(key="L74"),
        Field(key="L75"),
        Field(key="L76"),
        Field(key="L91"),
        Field(key="L112"),
        Field(key="L113"),
        Field(key="Your1stName:", terminator="\n"),
        Field(key="YourLastName:", terminator="\n"),
        Field(key="YourSocSec#:", terminator="\n"),
        Field(key="Spouse1stName:", terminator="\n"),
        Field(key="SpouseLastName:", terminator="\n"),
        Field(key="SpouseSocSec#:", terminator="\n"),
        Field(key="Number&Street:", terminator="\n"),
        Field(key="Apt#:", terminator="\n"),
        Field(key="Town:", terminator="\n"),
        Field(key="Zipcode:", terminator="\n"),
        Field(key="YourDOB:", terminator="\n"),
        Field(key="SpouseDOB:", terminator="\n"),
    ),
    output_wrap=(),
)
