use tenforty_runtime::{FilingStatus, Graph, Runtime};

fn main() {
    let json = include_str!("us_1040_2025_dsl.json");

    println!("Attempting to parse DSL-generated JSON...");
    let graph = match Graph::from_json(json) {
        Ok(g) => {
            println!("SUCCESS: Parsed graph with {} nodes", g.nodes.len());
            g
        }
        Err(e) => {
            eprintln!("FAILED to parse JSON: {}", e);
            std::process::exit(1);
        }
    };

    println!("\nGraph info:");
    if let Some(ref meta) = graph.meta {
        println!("  Form ID: {:?}", meta.form_id);
        println!("  Year: {:?}", meta.year);
        println!("  Generated by: {:?}", meta.generated_by);
    }
    println!("  Inputs: {} nodes", graph.inputs.len());
    println!("  Outputs: {} nodes", graph.outputs.len());
    println!("  Tables: {} tables", graph.tables.len());

    // Try to evaluate
    println!("\nAttempting basic evaluation...");
    let mut rt = Runtime::new(&graph, FilingStatus::Single);

    // Set all inputs to 0 first
    for &input_id in &graph.inputs {
        rt.set_by_id(input_id, 0.0);
    }

    // Set some basic input
    // Looking at the DSL JSON, L1a is wages (node name "L1a")
    if let Some(node) = graph.node_by_name("L1a") {
        rt.set_by_id(node.id, 100000.0);
        println!("  Set L1a (wages) = $100,000");
    }

    // Try to evaluate outputs
    for &output_id in &graph.outputs {
        if let Some(node) = graph.nodes.get(&output_id) {
            match rt.eval_node(output_id) {
                Ok(value) => {
                    let name = node.name.as_deref().unwrap_or("(unnamed)");
                    println!("  Output {}: {} = ${:.2}", output_id, name, value);
                }
                Err(e) => {
                    let name = node.name.as_deref().unwrap_or("(unnamed)");
                    println!("  Output {}: {} = ERROR: {:?}", output_id, name, e);
                }
            }
        }
    }

    println!("\nE2E Test PASSED!");
}
